import type { Project } from "@/features/projects/types";

export const defaultProjects: Project[] = [
  {
    id: "default-hotel-kitchen",
    slug: "hotel-kitchen-prep-area",
    title: "Hotel Kitchen Prep Area",
    scope: "Prep Tables, Sinks, Wall Shelving",
    image_url: "/images/projects/hotel-kitchen.png",
    industry: "Hospitality",
    location: "Karachi, Pakistan",
    materials: "SS 304, #4 satin finish",
    description:
      "Full prep zone fabrication for a high-volume hotel kitchen including welded prep tables, compartment sinks, and wall shelving.",
    specs: "SS 304 | 1.2mm tops | Seamless welds | Adjustable bullet feet",
    sort_order: 10,
    published: true,
    created_at: "",
  },
  {
    id: "default-hospital-prep",
    slug: "hospital-sterile-prep-station",
    title: "Hospital Sterile Prep Station",
    scope: "Custom Fabrication, Seamless Welds",
    image_url: "/images/projects/hospital-prep.png",
    industry: "Healthcare",
    location: "Karachi, Pakistan",
    materials: "SS 304, hygienic radiused corners",
    description:
      "Sterile prep workstations built for hospital infection-control requirements with seamless welds and easy-clean surfaces.",
    specs: "SS 304 | Radiused corners | Fully welded bowls",
    sort_order: 20,
    published: true,
    created_at: "",
  },
  {
    id: "default-restaurant-line",
    slug: "restaurant-cooking-line",
    title: "Restaurant Cooking Line",
    scope: "Exhaust Hood, Equipment Stands",
    image_url: "/images/projects/restaurant-line.png",
    industry: "Food Service",
    location: "Lahore, Pakistan",
    materials: "SS 304 / SS 430 hood sections",
    description:
      "Cookline exhaust hood and equipment stands for a busy restaurant kitchen.",
    specs: "Canopy hood | Baffle filters | Equipment stands",
    sort_order: 30,
    published: true,
    created_at: "",
  },
  {
    id: "default-pharma-cleanroom",
    slug: "pharma-cleanroom-workbench",
    title: "Pharma Cleanroom Workbench",
    scope: "Hygienic Workstations, Drawers",
    image_url: "/images/projects/pharma-cleanroom.png",
    industry: "Pharmaceutical",
    location: "Karachi, Pakistan",
    materials: "SS 304, electropolished-ready finish",
    description:
      "Cleanroom-grade workbenches with integrated drawer storage for pharmaceutical production.",
    specs: "SS 304 | Drawer units | Hygienic design",
    sort_order: 40,
    published: true,
    created_at: "",
  },
  {
    id: "default-qsr-kitchen",
    slug: "qsr-back-of-house",
    title: "QSR Back-of-House",
    scope: "Prep Counters, Assembly Tables",
    image_url: "/images/projects/qsr-kitchen.png",
    industry: "QSR",
    location: "Islamabad, Pakistan",
    materials: "SS 304 prep surfaces",
    description:
      "Fast-casual back-of-house prep counters and assembly tables for high-throughput service.",
    specs: "Prep counters | Assembly tables | SS 304",
    sort_order: 50,
    published: true,
    created_at: "",
  },
  {
    id: "default-industrial-cafeteria",
    slug: "industrial-cafeteria-serving-line",
    title: "Industrial Cafeteria Serving Line",
    scope: "Hot/Cold Displays, Tray Slides",
    image_url: "/images/projects/industrial-cafeteria.png",
    industry: "Industrial",
    location: "Karachi, Pakistan",
    materials: "SS 304 serving line components",
    description:
      "Serving line with hot/cold display sections and tray slides for an industrial cafeteria.",
    specs: "Hot/cold displays | Tray slides | Custom lengths",
    sort_order: 60,
    published: true,
    created_at: "",
  },
  {
    id: "default-custom-shelving",
    slug: "cold-storage-shelving",
    title: "Cold Storage Shelving",
    scope: "Heavy-Duty Racking, Slotted Shelves",
    image_url: "/images/projects/custom-shelving.png",
    industry: "Cold Chain",
    location: "Karachi, Pakistan",
    materials: "SS 304 slotted shelving",
    description:
      "Heavy-duty cold room shelving designed for wash-down and corrosion resistance.",
    specs: "Slotted shelves | Heavy-duty brackets | SS 304",
    sort_order: 70,
    published: true,
    created_at: "",
  },
  {
    id: "default-grease-trap",
    slug: "commercial-grease-interceptor",
    title: "Commercial Grease Interceptor",
    scope: "Custom Sized Grease Trap, Plumbing",
    image_url: "/images/projects/grease-trap.png",
    industry: "Food Service",
    location: "Karachi, Pakistan",
    materials: "SS 304, 2.0mm gauge",
    description:
      "Custom-sized grease interceptor with watertight welded construction for commercial kitchen drainage.",
    specs: "SS 304 | 2.0mm | Watertight welds",
    sort_order: 80,
    published: true,
    created_at: "",
  },
];

export function getDefaultProjectBySlug(slug: string) {
  return defaultProjects.find((project) => project.slug === slug) ?? null;
}
